# Jekyll Defaults
title: Haha-hoho
description: Just My Archives
baseurl: "" # the subpath of your site, e.g. /blog

url: "http://localhost:3000"
github: http://github.com/tnguyen/blueface
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: Tags
  url: /tags/
